#!/usr/bin/python
# -*- coding: utf-8 -*-
import pygame

WIN_WIDTH = 576
WINDOW_HEIGHT = 680

COLOR_WHITE = (255, 255, 255)
COLOR_YELLOW = (255, 255, 0)
COLOR_RED = (255, 0, 0)
COLOR_GREEN = (0, 255, 0)
COLOR_BLUE = (0, 150, 255)
COLOR_BLACK = (0, 0, 0)

MENU_OPTION = (
    '1 PLAYER',
    '2 PLAYERS',
    'EXIT',
)

ENEMY_EVENT = pygame.USEREVENT + 1
SPAWN_TIME = 1200

ENTITY_HEALTH = {
    'Player': 100,
    'Missile': 1,
    'Enemy1': 1,
    'Enemy2': 3,
    'Explosion': 1,
}

ENTITY_SPEED = {
    'Enemy1': 3,
    'Enemy2': 2,
}

BASE_HEALTH = 10
WIN_SCORE = 20000

DIR_LEFT = 0
DIR_CENTER_LEFT = 1
DIR_CENTER = 2
DIR_CENTER_RIGHT = 3
DIR_RIGHT = 4

MISSILE_ANGLES = {
    DIR_LEFT: 135,
    DIR_CENTER_LEFT: 115,
    DIR_CENTER: 90,
    DIR_CENTER_RIGHT: 65,
    DIR_RIGHT: 45,
}

PLAYER1_ROTATE_LEFT = pygame.K_a
PLAYER1_ROTATE_RIGHT = pygame.K_d
PLAYER1_SHOOT = pygame.K_SPACE

PLAYER2_ROTATE_LEFT = pygame.K_LEFT
PLAYER2_ROTATE_RIGHT = pygame.K_RIGHT
PLAYER2_SHOOT = pygame.K_RETURN